### ISSUE TITLE
XML Format Problem

### ISSUE THREAD

**Issue by daikinomura** [globalwordnet/english-wordnet#31]
In editing XML files, I am facing the same troubles that Alexandre mentioned in Issue 26, 30. I would like to discuss this issue and find some solution to these problems. He listed two points.  

1. the size of each lexicographer file is almost 10x times bigger than the original WordNet txt files
--My vim almost freeze when I search a word in a huge file(e.x., adj.all). So I use "grep -n" and jump to the line number(Command line grep is faster than editor's search). However, this might be a problem.  

2. synsets are not self-contained in the same file region
--Wordform relations are separated from "synset tag" and put them in a "sense tag". Although this might be an emphasis of word-form independence from word-meaning, this makes it difficult to grasp the overview of a synset in this XML.

There are 4 kinds of updates in WordNet: def, meaning-link, wordform-link, and wordform itself. I can handle for def but it is difficult for meaning-link, wordform-link, and wordform. 

Is there a way to make things easy for link and wordform?

**Comment by jmccrae** [comment]
I think Daiki and Alexandre have a point here, XML is very verbose and the files are quiet difficult to work with. On the other hand, the development of the XML format took a long time and it is important that the GWA still supports this format. Furthermore, it is important that we keep all the information that is in the current XML format. If we look at a couple of current entries

```xml
<LexicalEntry id="ewn-scalp-n">
  <Lemma writtenForm="scalp" partOfSpeech="n"/>
  <Sense id="ewn-scalp-n-05547580-01" synset="ewn-05547580-n" dc:identifier="scalp%1:08:00::">
    <SenseRelation relType="derivation" target="ewn-scalp-v-00198852-01"/> <!-- scalp -->
    </Sense>
</LexicalEntry>
<!-- scalp -->
<Synset id="ewn-05547580-n" ili="i66033" partOfSpeech="n" dc:subject="noun.body">
  <Definition>the skin that covers the top of the head</Definition>
  <SynsetRelation relType="hypernym" target="ewn-05245612-n"/> <!-- cutis, tegument, skin -->
  <SynsetRelation relType="holo_part" target="ewn-05546771-n"/> <!-- human head -->
  <Example>&quot;they wanted to take his scalp as a trophy&quot;</Example>
</Synset>
```
We see the following

* `id` could probably be inferred for lexical entries
* The `Lemma` tag could be simplified
* `id` on sense could be skipped 
* `SenseRelation`s and `SynsetRelation`s could be simplified
* `subject` is perhaps not required (as it is always the same in the file

Putting this all together I would propose a simple YAML syntax that can be used to generate the XML

```yaml
lexicalEntry:
    - lemma: scalp
      partOfSpeech: n
      sense:
          - synset: 05547580-n
            identifier: "scalp%1:08:00::"
            derivation: 
                - scalp-00198852-v

synset:
    - id: 05547580-n
      ili: i66033
      partOfSpeech: n
      definition:
          - the skin that covers the top of the head
      example:
          - "\"they wanted to take his scalp as a trophy\""
      hypernym: 
          - 05245612-n
      holo_part:
          - 05546771-n
```
This would significantly compact the files (I guess to about 60% of the current size), while still maintaining a 1:1 correspondence with the GlobalWordNet standard format.

**Comment by arademaker** [comment]
We don't need the quotes in the examples since we may infer that examples, when combined into the gloss, need quote.

We have already scripts to convert our txt format (that with small adaptation can turn to be YAML too) to XML. But in our format, we moved away from the synset ids. We kept a mapping from sense ids to synset ids. See https://github.com/own-pt/own-en/tree/master/mappings

Our entry would be:

```yaml
w: scalp drf verb.change:scalp
hyper: skin
hp: human_head
g: the skin that covers the top of the head
e: they wanted to take his scalp as a trophy
```

I also prefer longer names for the relations, that could be adapted for sure. This format is kind of inspired by bibliography records like https://en.wikipedia.org/wiki/RIS_(file_format).

The use of two different structures for `lexicalEntry` and `synset` will not solve the problem (2) above. I don't see why we need to keep two different structures. We could just have the synsets and its senses? Moreover, I am not convinced that we just add ILI ids to the resource. Do we have already a stable way to edit, browse and search ILI? But this is not the main problem. 

Comments?

**Comment by daikinomura** [comment]
Hi John and Alexandre.

1. YAML
This XML depends on comments.  We understand what is the holonym part of the scalp by  XML comment "-- human head --".  So the YAML may also need heavy comments.  Let's give it a try if we could. Almost John and I are the only commiter of this repository. That must be a problem.

2. synsets are not self-contained in the same file region
As Alexandre points out, we don't have anything for this problem. Is it possible to output the synset tag of "scalp", just below the lexicalEntry of the "scalp"?  Is it possible to make "lexicalEntry" and "synset" to be near?
 
 3. Back-end Database.
I have thought this is an output text from some back-end database. If compatibility is the problem, there must be some better way. Could I have the opinion of back-end database? 

I would like to have Francis Bond's opinion about this problem, if I could.  I am thinking you are the designer of the back-end database. I am sorry if I made a wrong guess.

Regards.

**Comment by arademaker** [comment]
How versions are numbered and increased ?

**Comment by arademaker** [comment]
I didn’t really follow the arguments in 

> Actually there are many examples where the quote is followed by an attribution, the quotes in the examples are part of this format.

Can you give an example?

**Comment by jmccrae** [comment]
The plan can be seen from the milestones of the project: 3.2 is only technical issues, 3.3 integrates other resources and fixes some issues, 3.4 deals with deeper issues and prepare for 4.0.

Example of a more complex LexicalEntry
https://github.com/globalwordnet/english-wordnet/blob/325f119f63c09486bcd19991c29e0a477a4c3093/src/wn31-verb.weather.xml#L106

Example of an attributed quote:
https://github.com/globalwordnet/english-wordnet/blob/325f119f63c09486bcd19991c29e0a477a4c3093/src/wn31-noun.phenomenon.xml#L6489

**Comment by arademaker** [comment]
hi @jmccrae , thank you for the links. 

About the lexical entries, it looks like we have more info than originally presented in PWN, am I right? In PWN I don't recall inflected forms nor expanded/contextualized subcategorization frames. 

On the other hand, the README file of this project says: 

> This Wordnet is an attempt to make it easier to provide feedback in the form of patches to the Princeton Wordnet.

and the list of acceptable chances emphasizes minor changes in PWN... Sorry, I am lost. Where did this information come from? 

Regarding the attributed quote, most examples are between quotes so I assumed that quotes were used as delimiters for the examples. But you are right, the original PWN documentation doesn't say much about gloss format (https://wordnet.princeton.edu/documentation/wndb5wn). We may need to revise it in our files, the quotes are not delimiters but really quotes for texts that may or may not have additional words before/after.

**Comment by jmccrae** [comment]
All the information is available as part of Princeton WordNet. The variant forms are from the `*.exc` files and the frames are combined from `data.verb` and `sents.vrb`.

The attribution isn't documented but the exact format was validated as part of the extraction process. I agree that it would be good to revise this so that double quotes around every example is not necessary, but for the moment we are sticking close to the PWN mechanism.

**Comment by arademaker** [comment]
About the `SyntacticBehaviour` tag, my mistake, they are the verb frames, I didn't notice it. thank you.

**Comment by jmccrae** [comment]
I have started working on creating a YAML version that is directly compatible with the current XML version but much more compact:

https://github.com/globalwordnet/english-wordnet/tree/yaml/src/yaml

Example of an entry

```yaml
able:
  a:
    senses:
    - antonym:
      - unable%3_00_00
      derivation:
      - ability%1_09_00
      - ability%1_07_00
      key: able%3_00_00
      synset: 00001740-a
  s:
    senses:
    - derivation:
      - ability%1_09_00
      - ability%1_07_00
      key: able%5_00_00_competent_00
      synset: 00512273-s
    - derivation:
      - ability%1_09_00
      - ability%1_07_00
      key: able%5_00_00_capable_00
      synset: 00307461-s
    - key: able%5_00_00_fit_01
      synset: 01021031-s
```

Example of a synset:

```yaml
00001740-a:
  attribute:
  - 05207437-n
  - 05624029-n
  definitions:
  - (usually followed by `to') having the necessary means or skill or know-how or
    authority to do something
  entries:
  - able
  examples:
  - '"able to swim"'
  - '"she was able to program her computer"'
  - '"we were at last able to buy a car"'
  - '"able to get a grant for the project"'
  ili: i1
  pos: a
```

NB: We will remove the ugly quotes on the examples with issue #143 
NB: Syntactic behaviour isn't handled yet. It will also be very simple though.

These files are much smaller by about 1/3 of the size and should be much easier to work with.
