### ISSUE TITLE
Merge non-satellite and satellite adjective entries

### ISSUE THREAD

**Issue by 1313ou** [globalwordnet/english-wordnet#774]
OEWN considers there are 2 distinct lexical entries

`<LexicalEntry id="oewn-critical-a"> 
`5 senses, n=0,1,2,3,4
`<LexicalEntry id="oewn-critical-s"> 
`2 senses, n=0,1

They do not merge because they have distinct IDs.

I think this is erroneous because they do not diverge in other respects (_a_ or _s_ simply codes if it's the head of a adjective cluster or a satellite), notably pronunciation: they have the same written form and pronunciation, unlike for instance 'row' [ou] and 'row' [au] where the divergence in pronunciation warrants their being distinct.

According to PWN3.1, the senses of lexical item 'critical' are, in usage-decreasing order:

A) synset="oewn-00650564-a" marked by a tendency to find and call attention to errors
B) synset="oewn-00654957-a" at or of a point at which a property or phenomenon suffers an abrupt change
C) synset="oewn-00652608-a" characterized by careful evaluation
D) synset="oewn-00907116-s "urgently needed
E) synset="oewn-00653599-a" forming or having the nature of a turning point
F) synset="oewn-02841530-a" being in or verging on a state of crisis
G) synset="oewn-00659155-s" of or involving or characteristic of critics

What we find in OEWN is this:

LUa:
```
<LexicalEntry id="oewn-critical-a">
   <Sense id="oewn-critical__3.00.01.." n="0" synset="oewn-00650564-a" sense A
   <Sense id="oewn-critical__3.00.04.." n="1" synset="oewn-00654957-a" sense B
   <Sense id="oewn-critical__3.00.02.." n="2" synset="oewn-00652608-a" sense C
   <Sense id="oewn-critical__3.00.03.." n="3" synset="oewn-00653599-a" sense E
   <Sense id="oewn-critical__3.01.00.." n="4" synset="oewn-02841530-a" sense F
</LexicalEntry>

```
LUs:
```
<LexicalEntry id="oewn-critical-s">
   <Sense id="oewn-critical__5.00.00.indispensable.00" n="0" synset="oewn-00907116-s" sense D
   <Sense id="oewn-critical__5.00.00.crucial.00"       n="1" synset="oewn-00659155-s" sense G
</LexicalEntry>

```
Note that
-Each LexicalEntry has its own 0-based independent ordering.
-The final merged Lexical entry should go "_aA aB aC sD aE aF sG_" with **intertwined** senses from LUa and LUs.

The problem is not specific to XML or WNDB forms but also YAML where two distinct entries are to be found. The ordering of senses is also lost. Here are the (skeleton) YAML entries:

```
critical:
  a:
    pronunciation:
    - value: ˈkɹɪtɪkəl
    sense:
      id: 'critical%3:00:01::'
      id: 'critical%3:00:04::'
      id: 'critical%3:00:02::'
      id: 'critical%3:00:03::'
      id: 'critical%3:01:00::'
  s:
    pronunciation:
    - value: ˈkɹɪtɪkəl
    sense:
      id: critical%5:00:00:indispensable:00
      id: critical%5:00:00:crucial:00

```
Should you want to merge these 2 LexicalUnits into one, the ordering information is not available. It has been lost and **there is no way to retrieve the intertwined ordering of senses**.

This should happen whenever an adjective belongs to both a (heads) and s (satellites) POS.

Let me add it's totally legitimate to want the senses of 'critical' sorted by usage without having to deal with 2 pseudo entries.
