### ISSUE TITLE
Nuisance inconsistencies

### ISSUE THREAD

**Issue by 1313ou** [globalwordnet/english-wordnet#880]
The entry-to-synset (_synset_ attr) and synset-to-entry (_members_ attr) relations are redundant but the latter is expected to be consistent with the former if mandatory.

Lexical entry **nuisance** refers to synset 05838383-n as one of its senses :

```
nuisance:
  n:
    pronunciation:
    - value: ˈnusəns
      variety: US
    - value: ˈnjuːsəns
      variety: GB
    sense:
    - id: 'nuisance%1:09:00::'
      synset: 05838851-n
    - id: 'nuisance%1:09:01::'
      synset: 05838383-n

```
while the (2nd) synset does not count it as one of its members :

```
05838383-n:
  definition:
  - something or someone that causes trouble; a source of unhappiness
  example:
  - a bit of a bother
  - he's not a friend, he's an infliction
  - washing dishes was a pain in the neck before we got a dish washer
  hypernym:
  - 05837804-n
  ili: i67516
  members:
  - annoyance
  - bother
  - botheration
  - pain
  - infliction
  - pain in the neck
  - pain in the ass
  partOfSpeech: n

```

This is indeed a nuisance if  the inverse relation is not present and this absence has evaded consistency checks. It's not the only case (see below: there two cases).
The choice of redundancy is bound to lead to this sort of situation: inconsistencies. This why you did away with XML (good point here!)

**Comment by 1313ou** [comment]
Also (but there may be another problem here):

```
entries-y.yaml
--------------
Yellow race:
-  n:
-    sense:
- id: 'yellow_race%1:18:00::'
-      synset: 86191087-n

```
```
noun.persons.yaml
-----------------
86191087-n:
  definition:
  - an Asian race
  hypernym:
  - 07984596-n
  members:
  - Mongolian race
  - Mongoloid race
  mero_member:
  - 84278296-n
  partOfSpeech: n

```
