### ISSUE TITLE
XML '-xx-' escaping sneaking into YAML

### ISSUE THREAD

**Issue by 1313ou** [globalwordnet/english-wordnet#898]
```
entries-l.yaml:    - id: 'lgbtqia-pl-%1:14:00::'
entries-l.yaml:    - id: 'lgbt-pl-%1:14:00::'

```
are the only entries where the id  is escaped with the '-xx-' scheme intended to make them valid **XML** IDs

**Comment by jmccrae** [comment]
Not sure if this is a bug. I would note that we have both 'LBGT' and 'LGBT+' now so we do need to distinguish these lemmas and ideally without creating invalid identifiers in any serialization.

**Comment by 1313ou** [comment]
It's either a bug or inconsistent: you choose.

The following entries

```
LGBT:
  n:
    sense:
    - id: 'lgbt%1:14:00::'
      synset: 84123305-n
LGBTQ:
  n:
    sense:
    - id: 'lgbtq%1:14:00::'
      synset: 84123305-n
LGBTQIA:
  n:
    sense:
    - id: 'lgbtqia%1:14:00::'
      synset: 84123305-n
LGBTQIA+:
  n:
    sense:
    - id: 'lgbtqia+%1:14:00::'
      synset: 84123305-n
LGBT+:
  n:
    sense:
    - id: 'lgbt+%1:14:00::'
      synset: 84123305-n

```      
work fine and are gracefully handled by org.yaml's Snake library. No lemma is left out and all 5 flavours are present.
     
Historically the _two-characters-between-quotes_ scheme was introduced when the sensekeys were meant to replace the old sense IDs and you realized that the sensekeys didn't qualify as valid XML IDs.
The sensekeys were then '_mapped_' to valid XML IDs thanks to this scheme: offending characters were replaced with two letters recalling the name of the character enclosed between two dashes.

But the scope of this mapping was limited to XML: none of this coding actually appears in YAML as witnessed by

`egrep -B4 '\-(ap|lb|rb|sl|cm|ex|cl|pl|sp)\-' entries*`

YAML does not define what a valid ID is nor does it define what an ID is.

With one notable exception, inherent to YAML: the single quote that has to be escaped the way SQL does, by doubling it.

```
 '''tween':
  r:
    sense:
    - id: '''tween%4:02:00::'
      synset: 00252367-r
      

```
But the YAML libraries handle it without needing extra software (your 'unmapping' function). YAML is perfectly content with having any string as ID: the quotes enclosing it make it opaque so the id field currently IS the sensekey.

The rule is simple: you make the sensekey by lower-casing the lemma and replacing space with underscore (same rule as in PWNXX): all existing software proceeds this way when it has to build a key.

BTW other _weird_ keys include
```
    - id: '''tween%4:02:00::'
    - id: 'prince_william,_duke_of_cumberland%1:18:01::'
    - id: 'yahoo!%1:10:01::'
    - id: 'i/o_device%1:06:01::'
    - id: 'capital:_critique_of_political_economy%1:10:01::'

```
but none of -ap-,-cm-,-ex-,-sl-,-cl- respectively appear in the sensekey. And it does not run into trouble.

You are importing this scheme from XML into YAML: it's a first, it's adhoc, it's undocumented, and it's not needed. Just add the -pl- coding to the mapping/unmapping functions.
