### ISSUE TITLE
Sense duplicates

### ISSUE THREAD

**Issue by 1313ou** [globalwordnet/english-wordnet#958]
Tools allow senses to be stated multiple times (leading to sense aliases).
Which they shouldn't.

from entries-f.yaml:

```
fracture:
  v:
	...
    sense:
	...
    - derivation:
      - 'fracture%1:04:00::'
      - 'fracture%1:26:00::'
      id: 'fracture%2:29:00::'
      sent:
      - Did he fracture his foot?
      subcat:
      - vtai
      synset: 00107543-v

    - derivation:
      - 'fracture%1:04:00::'
      - 'fracture%1:26:00::'
      id: 'fracture%2:29:11::'
      subcat:
      - vtai
      synset: 00107543-v

```
the last sense is a repeat of the last but one since they target the same synset (senses are understood to be the membership function that takes a lemma and a synset).
See [issue 959](https://github.com/globalwordnet/english-wordnet/issues/959)
