### ISSUE TITLE
Member duplicates

### ISSUE THREAD

**Issue by 1313ou** [globalwordnet/english-wordnet#959]
Tools do not catch duplicate synset members:

from verb.body.yaml:

```
00107543-v:
  definition:
  - fracture a bone of
  ...
  members:
  - fracture
  - break
  - fracture
  partOfSpeech: v
```
Cause or consequence of [issue 958](https://github.com/globalwordnet/english-wordnet/issues/958)
