### ISSUE TITLE
Incorrect plural form for duodenum

### ISSUE THREAD

**Issue by goodmami** [globalwordnet/english-wordnet#988]
**Affected entry**

* `duodenum` (n)

https://github.com/globalwordnet/english-wordnet/blob/f2528e218eb6034696aff5023d5de54152cb8f9d/src/yaml/entries-d.yaml#L68429-L68433

**Proposed changes**

Change alternative word forms as follows:

* `duonena` → `duodena`
* `duonenums` → `duodenums`

```yaml
duodenum:
  n:
    form:
    - duodena
    - duodenums
```

**Motivation**

This issue was raised in #800, but the fix in #878 introduced a slightly different error.
